# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9569d3da79c51ffb74374e46d42a7c33bae18654d807a9b50af9997d4cf8dd363f312679d421fe9a017bfa917e5fcddf412567c626c312b983f6a354f3f5c21a

test:
  secret_key_base: 83876a68e9515246bdf3e60d0f16c348967be4e857bbb6380b7e676f9760e783bad7071e858c122a3dc6f78404bc6ab4ebf52b8536add851891157b1a578d143

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
